### ISSUE TITLE
Extend bitbucket_workspace to add plan information.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-bitbucket#28]
**References**
To get information about the plan and relation consumption metrics if any

![image](https://user-images.githubusercontent.com/26873346/125456646-39f811e1-1075-4341-9edd-b06987ef2dda.png)

**Comment by sayan133** [comment]
Not getting any direct API as of now. The API `/rest/api/1.0/admin/license` was available in Bitbucket 1.0 API, but currently, it is deprecated & cannot be used.
Deprecation notice: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/
