### ISSUE TITLE
Add bitbucket_workspace_member table with associated group info.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-bitbucket#30]
**Is your feature request related to a problem? Please describe.**
Current table does not provide info for associated grp info.  Good to have this col is captured. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bigdatasourav** [comment]
https://github.com/turbot/steampipe-plugin-bitbucket/issues/4

**Comment by bigdatasourav** [comment]
https://github.com/turbot/steampipe-plugin-bitbucket/issues/41
