### ISSUE TITLE
Add table bitbucket_repository_wiki

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-bitbucket#34]
**References**
Gather wiki setting details for Bitbucket.

![image](https://user-images.githubusercontent.com/26873346/125617417-e5f6dc5f-d1cf-4468-979c-0b69e1b0273f.png)

**Comment by sayan133** [comment]
As of now, there is no specific API for the wiki settings. However, there is a column `has_wiki` in the updated repository table (https://github.com/turbot/steampipe-plugin-bitbucket/pull/40) through which we can check whether the repository has any Wiki or not.
