### ISSUE TITLE
Add table bitbucket_ pipelines_deployments

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-bitbucket#37]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

**Comment by sayan133** [comment]
API Reference: https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/deployments/
