### ISSUE TITLE
Unable to get information about more than 10 branches in Bitbucket Plugin

### ISSUE THREAD

**Issue by justinepdevasia** [turbot/steampipe-plugin-bitbucket#57]
**Describe the bug**
Unable to get information about more than 10 branches.

**Steampipe version (`steampipe -v`)**
v0.15.3

**Plugin version (`steampipe plugin list`)**
v0.2.1

**To reproduce**
Steps to reproduce the behavior .

Need to have more than 10 branches in a repository

```
select
  count(*)
from
  bitbucket_branch
where
  repository_full_name='workspace-name/repo-name'
```

**Expected behavior**
Get the count of all branches present in the repo

**Additional context**
Plugin: Bitbucket
Currently giving maximum branch count as 10, even if the actual count is greater.

**Comment by justinepdevasia** [comment]
limiting is working but still getting only 10 branches at max.
```
select
  count(*)
from
  bitbucket_branch
where
  repository_full_name='workspace-name/repo-name'
```

**Comment by cbruno10** [comment]
Hi @justinepdevasia , can you please share your Steampipe CLI + plugin version you're using for the latest query? Also, can you please try restarting your Steampipe service (`steampipe service stop --force`, `steampipe service start`) and then try the query again? Thanks!

**Comment by justinepdevasia** [comment]
Hi @cbruno10, after force stop and restart `steampipe service stop --force` Its working perfectly !!
Thank you.
steampipe version - 0.15.3
bitbucket version - 0.2.2
