### ISSUE TITLE
Support on-prem Bitbucket Server

### ISSUE THREAD

**Issue by fabian-zeindl-oebb** [turbot/steampipe-plugin-bitbucket#59]
**Is your feature request related to a problem? Please describe.**
This plugin does not work with bitbucket-server (on-premise) installation, as it's rest-API is different than hosted bitbucket.

**Describe the solution you'd like**
Plugin updated to work with the on-prem API

**Describe alternatives you've considered**
None, I need this to be able to use steampipe.

**Comment by cbruno10** [comment]
Hey @fabian-zeindl-oebb , thanks for opening this issue!

I'm not very familiar with Bitbucket, but it looks like Bitbucket server is using v1.0 of the API, while Bitbucket cloud is using v2.0. The SDK we're using, [go-bitbucket](https://github.com/ktrysmt/go-bitbucket) doesn't seem to support v1.0 as per their [FAQ](https://github.com/ktrysmt/go-bitbucket#support-bitbucket-api-v10-).

There is another library, [go-bitbucket-v1](https://github.com/gfleury/go-bitbucket-v1) that appears to be compatible with the Bitbucket server API version, though I haven't given it a try before. There may be other libraries, but this one seems to be the most popular.

One approach to implementing support would be:
- Add a new config argument, e.g., `api_version`, which defaults to `v2`, but could also accept `v1`
- The plugin and its tables would use this config arg to determine which APIs to call to list/get/etc.
- Thus both libraries (`go-github` and `go-github-v1`) would be used in this plugin

If anyone would like to try adding support for v1 of the API, I believe the approach above would work, though it would require some refactoring of the plugin to allow v1 and v2 to work side-by-side. As a starting point, testing out the v1 SDK on one table could help prove if that SDK is sufficient for a wider rollout.

**Comment by e-gineer** [comment]
While I'm sure it's still in active use and important to many organizations, it's also worth noting that Bitbucket Server has been deprecated by Atlassian - https://www.atlassian.com/migration/assess/journey-to-cloud

**Comment by fabian-zeindl-oebb** [comment]
Thanks for the analysis. I also know that bitbucket-server will be deprecated, but it will still be a while until then.
