### ISSUE TITLE
Please provide support for environment variables for username and app password or access token

### ISSUE THREAD

**Issue by ravindrakmr** [turbot/steampipe-plugin-bitbucket#76]
It would be nice if this plugin can support using environment variables for Bitbucket username and app password, or even better if it can support access tokens which are more generic in nature and don't require a specific user.

**Comment by cbruno10** [comment]
Hi @ravindrakmr , we actually do support environment variables today, e.g.,https://github.com/turbot/steampipe-plugin-bitbucket/blob/main/bitbucket/utils.go#L24-L26

Our documentation doesn't reflect this though, so we'll look to update it.
