### ISSUE TITLE
Include a boolean field for "Branch Restrictions Inheritance" or similar on the bitbucket_branch_restriction or both bitbucket_my_repository and bitbucket_repository

### ISSUE THREAD

**Issue by oaulicino** [turbot/steampipe-plugin-bitbucket#84]
**Is your feature request related to a problem? Please describe.**
I have been working with the bitbucket plugin for a while now and one of my use cases refers to the "bitbucket_branch_restriction" table, so that I can find out if there are repositories with insecure permissions. My issue right now is that there are repositories that inherit branch restrictions from the project, as you can see here:
![image](https://github.com/turbot/steampipe-plugin-bitbucket/assets/31516700/06480b4f-aba4-414d-ac54-548ab866ac85)
When I use the query to show branch restrictions for this particular repository, the result is as if it was not set, as you can see below, which is not true (inherited):
![image](https://github.com/turbot/steampipe-plugin-bitbucket/assets/31516700/6aeb4deb-28e0-44f7-b9e9-9c7400fc9a64)

**Describe the solution you'd like**
I believe that using the API endpoint below to include one extra column to the bitbucket_my_repository table could solve my problem temporarily, as there seems like a project settings api for querying branch restrictions at the project level does not exist yet (I requested it though):
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-repositories/#api-repositories-workspace-repo-slug-override-settings-get
One thing to note is that this endpoint won't work with the current personal access token, as you can see below:
![image](https://github.com/turbot/steampipe-plugin-bitbucket/assets/31516700/59876544-e015-4c90-aed6-3999a84c9f55)
For this api endpoint to work, we will need the Workspace Access Token, that can be created at: 
https://bitbucket.org/<COMPANY>/workspace/settings/access-tokens 
When it works correctly, the result should be like this:
![image](https://github.com/turbot/steampipe-plugin-bitbucket/assets/31516700/c1d9e1d1-16b1-4594-b119-425ec48950cc)

**Describe alternatives you've considered**
I have no other idea at the moment other than using the GUI, unfortunately.

**Additional context**
No other context I can offer here.

**Comment by ParthaI** [comment]
Hello @oaulicino, thank you for your detailed report on the issue.

We rely on the [SDK](https://pkg.go.dev/github.com/ktrysmt/go-bitbucke) for fetching and populating the column values in our tables. At present, this SDK lacks support for retrieving _Inherited_ branch restriction settings that are applied from the project level down to the repository level.

I have taken the initiative to submit a support request addressing this concern, which you can track here: [GitHub Issue #268](https://github.com/ktrysmt/go-bitbucket/issues/268). Once there is a resolution to this support issue, we will re-examine our own issue and implement the necessary updates.

Thank You!

**Comment by bigdatasourav** [comment]
Closing this issue for now, we will revisit this once we get an update from the above SDK issue.
